server:
  port: 8093

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.cbib9.mongodb.net/cryptocurrency_task?retryWrites=true&w=majority

app:
  config:
    currencyPairs:
      BTC: USD
      ETH: USD
      XRP: USD
    outputFileName: "file"