server:
  port: 8093

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.cbib9.mongodb.net/cryptocurrency_task?retryWrites=true&w=majority

app:
  configuration:
    currencyPairList[0]: BTC/USD
    currencyPairList[1]: ETH/USD
    currencyPairList[2]: XRP/USD

    dateFormat: yyyy-MM-dd HH:mm:ss
