server:
  port: 8093

spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "cryptocurrencies-info"

app:
  config:
    currencyPairs:
      BTC: USD
      ETH: USD
      XRP: USD
    outputFileName: "file"